name = input("What is your name? ")
print(f"Welcome {name} to our page. ")
favourite_colour = input("what is your favourite colour? ")
favourite_food = input("What is your favourite food? ")
print(f"{name}, My favourite colour is also {favourite_colour.lower()} same as you, and i also like {favourite_food}.")
favourite_place = input("What is your favourite place? ")
favourite_animal = input("What is your favourite animal? ")
print(f"{name}, {favourite_place} is a beautiful place. And {favourite_animal} is a beautiful animal. ")
print(f"Welcome {name}! Your favourite colour is {favourite_colour} and you love {favourite_food}.")
print(f"One day, you went to {favourite_place} with a {favourite_colour} {favourite_animal} while eating {favourite_food}!")